name: "Code Scanning and Validation"

on:
  push:
    branches: [ "main",  "dev" ]
  pull_request:
    branches: [ "main", "dev" ]
  schedule:
    - cron: '25 12 * * 0'

jobs:
  codeql:
    name: CodeQL Scanning
    runs-on: ubuntu-latest
    timeout-minutes: ${{ (matrix.language == 'swift' && 120) || 360 }}
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'python' ]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          python:
            - '**.py'
    - name: Initialize CodeQL
      if: steps.filter.outputs.python == 'true'
      uses: github/codeql-action/init@v2
      with:
        languages: ${{ matrix.language }}
    - name: Perform CodeQL Analysis
      if: steps.filter.outputs.python == 'true'
      uses: github/codeql-action/analyze@v2
      with:
        category: "/language:${{matrix.language}}"

  json-yaml-validate:
    name: JSON Validation
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          json-yaml:
            - '**.json'
            - '**.yaml'
            - '**.yml'
    - name: json-yaml-validate
      if: steps.filter.outputs.json-yaml == 'true'
      uses: GrantBirki/json-yaml-validate@v1.5.0
      with:
        comment: "true"

  workflow-keepalive:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@v1
